---
- hosts: debiantest

  become: true
  become_method: su
  become_user: root

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install packages
      apt:
        name: 
          - ncdu
          - git
          - vim
          - htop
          - sudo
          - wget
          - nfs-common
          - autofs
        state: present

    - name: Install mail packages
      apt:
        name: 
          - msmtp-mta
          - bsd-mailx
        state: present

    - name: Configure mail server
      template:
        src: "msmtprc.j2"
        dest: "/etc/msmtprc"
        mode: 0644
        # owner: root

    - name: Add user to sudoers
      user:
        name: '{{ debian_user }}'
        groups: sudo
        append: yes

    - name: Setting VIM
      copy:
        dest: "{{ item }}"
        content: |
          source $VIMRUNTIME/defaults.vim
          set mouse-=a
      with_items:
        - /home/{{ debian_user }}/.vimrc
        - /root/.vimrc

    - name: Add aliases
      blockinfile: 
        state: present
        insertafter: EOF
        dest: "{{ item }}"
        content: |
          alias ll='ls -lah --color'
      with_items:
        - /home/{{ debian_user }}/.bashrc
        - /root/.bashrc

    - name: Chown all user folders
      file:
        path: "/home/{{ debian_user }}"
        state: directory
        recurse: yes
        owner: "{{ debian_user }}"
        group: "{{ debian_user }}"

    - name: Add mail variables in crontab
      community.general.cronvar:
        name: "{{item.0}}"
        value: "{{ debian_smtp_user }}"
        user: "{{item.1}}"
      with_nested:
        - ['MAILTO', 'MAILFROM']
        - ["{{ debian_user }}", 'root']

    - name: change user passwords
      user:
        name: "{{ debian_user }}"
        state: present
        password: "{{ debian_user_password | password_hash('sha512') }}"

    - name: change root passwords
      user:
        name: "root"
        state: present
        password: "{{ debian_root_password | password_hash('sha512') }}"